### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [zacharee/MastodonRedirect#1]
First thanks for providing your app here! Sounds interesting. Can you please let us know what license you're using to protect it? There's none shown in the code, which makes it "all rights reserved" (i.e. "code available", but not FOSS; "just look but do not touch"). Also, is Bugsnag configured opt-in, or is it enabled by default?

**Comment by zacharee** [comment]
MIT license added. Bugsnag is enabled with no way to disable currently.

**Comment by IzzySoft** [comment]
Thanks a lot! Then let's raise visibility: with the next sync around 6 pm UTC (i.e. in less than 19h from now) your app will [become available](https://apt.izzysoft.de/packages/dev.zwander.mastodonredirect/) in my repo (unfortunately with the `Tracking` mark, due to Bugsnag being enabled by default – once that configuration is changed please let me know and I can remove that flag). If you like what you see, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme. Should you have some screenshots you wish added there, let me know where to find them and I'll add them.

**Comment by zacharee** [comment]
> Thanks a lot! Then let's raise visibility: with the next sync around 6 pm UTC (i.e. in less than 19h from now) your app will [become available](https://apt.izzysoft.de/packages/dev.zwander.mastodonredirect/) in my repo (unfortunately with the `Tracking` mark, due to Bugsnag being enabled by default – once that configuration is changed please let me know and I can remove that flag). If you like what you see, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme. Should you have some screenshots you wish added there, let me know where to find them and I'll add them.

1.1.1 has it disabled by default.

**Comment by IzzySoft** [comment]
Oh? Good, then let me remove the flag again. :star_struck:

**Comment by zacharee** [comment]
The `instances.social` connection isn't used in normal functioning of the app. I have it in an exported Activity that can only be launched with an Activity launcher for me to use to update the static list in the manifest.

**Comment by IzzySoft** [comment]
So it is not connected automatically? How does one select the domains? I gladly remove the NonFreeNet anti-feature then – and apologize for the misinterpretation, admitting I didn't make a test-run of the app to verify.

Maybe you could include a corresponding note with the Readme then as well? Going by the Readme, I expected a list of instances would probably be downloaded from there during setup (to make sure it's up-to-date).

**Comment by zacharee** [comment]
The deep links are specified at compile time in the manifest. I can update the readme to make that clearer.

**Comment by IzzySoft** [comment]
Thanks! Removed the AF meanwhile (effective with the next sync around 6 pm UTC).

**Comment by zacharee** [comment]
@IzzySoft I made some pretty foundational changes to the project structure (plus a new "variant" app) and I think it might've broken the build on your repo.

**Comment by IzzySoft** [comment]
Oof? Any action needed from my end? Or do you simply push an update fixing that?

**Comment by zacharee** [comment]
I'm not sure. I don't know how your build system is managing things. It's two APKs now, for the two variants. 

`lemmyredirect`
`mastodonredirect`

**Comment by IzzySoft** [comment]
If it's just that :smile:

* [Lemmy Redirect](https://apt.izzysoft.de/fdroid/index/apk/dev.zwander.lemmyredirect)
* [Mastodon Redirect](https://apt.izzysoft.de/fdroid/index/apk/dev.zwander.mastodonredirect)

Seems the last release did not provide a newer version for the latter, but apart from that I've updated the configs on my end accordingly. Setting up Fastlane (see my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688)) will be a bit tricky with 2 apps in the same repo, but even that would be possible if you wish (so you could control how your apps are presented); my repo supports custom locations for Fastlane, so no big deal there.

**Comment by zacharee** [comment]
Hmm Mastodon Redirect should be on 1.3.3 as well. Did the wrong APK upload to the Releases page?

**Comment by IzzySoft** [comment]
My updater says so, yes:

    repo/dev.zwander.mastodonredirect_8.apk already exists and is identical to the one we downloaded

Maybe you just forgot to increase `versionCode`?

**Comment by zacharee** [comment]
1.3.0 had a version code of 5, so I'm not sure what's going on there.

**Comment by IzzySoft** [comment]
```
$ wget https://github.com/zacharee/MastodonRedirect/releases/download/1.3.3/mastodonredirect-release.apk
$ aapt d badging mastodonredirect-release.apk | head -n 1
dev.zwander.mastodonredirect' versionCode='8' versionName='1.3.3'
```

Now I am lost. Wait, WTF is that?

```
$ iod repo get dev.zwander.mastodonredirect
dev.zwander.mastodonredirect: looking for 'https://api.github.com/repos/zacharee/MastodonRedirect/releases'
dev.zwander.mastodonredirect: checking tag '1.3.3'
dev.zwander.mastodonredirect: lastRelNo set to '1.3.3', checking for files
dev.zwander.mastodonredirect: Upstream file date (2023-08-03 15:39) is newer than ours (2023-07-22 19:46).
dev.zwander.mastodonredirect: returning ['1.3.3','https://github.com/zacharee/MastodonRedirect/releases/download/1.3.3/lemmyredirect-release.apk',1691069949]
dev.zwander.mastodonredirect: 1.3.0/1.3.3, https://github.com/zacharee/MastodonRedirect/releases: https://github.com/zacharee/MastodonRedirect/releases/download/1.3.3/lemmyredirect-release.apk
```

Why is it fetching the Lemmy one? RegEx is explicitly set to `/mastodon/i`. Oh, FFS… There's a `Mastodon` in the Lemmy-URL as well! Yikes! Let me see… (setting up the couter-part: the `ApkIgnore: /lemmy/i' and trying again) Ha! Yesyesyes:

```
$ iod repo get dev.zwander.mastodonredirect
dev.zwander.mastodonredirect: looking for 'https://api.github.com/repos/zacharee/MastodonRedirect/releases'
dev.zwander.mastodonredirect: checking tag '1.3.3'
dev.zwander.mastodonredirect: lastRelNo set to '1.3.3', checking for files
dev.zwander.mastodonredirect: Upstream file date (2023-08-03 15:38) is newer than ours (2023-07-22 19:46).
dev.zwander.mastodonredirect: returning ['1.3.3','https://github.com/zacharee/MastodonRedirect/releases/download/1.3.3/mastodonredirect-release.apk',1691069909]
dev.zwander.mastodonredirect: 1.3.0/1.3.3, https://github.com/zacharee/MastodonRedirect/releases: https://github.com/zacharee/MastodonRedirect/releases/download/1.3.3/mastodonredirect-release.apk
- Grabbing update for dev.zwander.mastodonredirect: OK
Binary files /web/ftp/repo/fdroid/repo/dev.zwander.mastodonredirect_8.apk and /web/ftp/repo/fdroid/repo/dev.zwander.mastodonredirect_1.3.3.apk differ
repo/dev.zwander.mastodonredirect_8.apk already exists, quarantining before replacing it with update '/web/ftp/repo/fdroid/repo/dev.zwander.mastodonredirect_1.3.3.apk'
- Checking 'repo/dev.zwander.mastodonredirect_8.apk' for libraries and malware …
dev.zwander.mastodonredirect: check if repo contains FUNDING.yml
dev.zwander.mastodonredirect: looking for 'https://api.github.com/repos/zacharee/MastodonRedirect/contents/.github'
dev.zwander.mastodonredirect: Github reports "Not Found" for https://api.github.com/repos/zacharee/MastodonRedirect/contents/.github
dev.zwander.mastodonredirect: looking for 'https://api.github.com/repos/zacharee/MastodonRedirect/contents/'
dev.zwander.mastodonredirect: no FUNDING.yml detected.
dev.zwander.mastodonredirect: no Fastlane configured, skipping Fastlane check.
```

Good you reached out, I'd have wondered for a while here. Latest version will show up with the next sync then (we just missed the current one by half an hour) – but at least it's fixed now!

**Comment by zacharee** [comment]
Thanks for looking into it! I would rename the repo but I don't want to break things yet again.

**Comment by IzzySoft** [comment]
All fine now! Should you split one day, please let me know. Thanks!

**Comment by zacharee** [comment]
Got another variant to add when/if you have time: `dev.zwander.peertuberedirect` (`peertuberedirect` module).

**Comment by IzzySoft** [comment]
Thanks @zacharee! A few questions there:

* why not combining the functionality into a single app? One isn't bound to a single Fediverse service. I e.g. use Mastodon and PeerTube frequently. Now let's assume I'd also use Lemmy, and I wanted those redirects on my Android device for all 3 of them. So I had to install 3 apps with 16 MB each to achieve that. Isn't that a bit overkill, especially for low-end devices?
* The new one has set the flag for unencrypted network traffic (`usesCleartextTraffic: true`), I guess the other ones have that as well but I didn't notice it back then as it's a new check I just added recently. Is that needed? As the app targets API33, this flag by default should be set to `false`. Any reason you have enabled it for?
* bugsnag is opt-in again, as with the other two?
* what about description and screenshots? There are screenshots in the Readme for the other two (which I've just added to their resp. apps here), but not for this one. You might consider setting up Fastlane structures for metadata of each, so you can define how they are presented and ensure those details are always up-to-date when making new releases. For guidance, be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) (Fastlane is the quasi-standard for that on Android apps). As you currently do not have those, the description of the other two apps in my repo was a bit outdated; I've just now updated the list of supported clients.

None of those are show-stoppers, so I'm adding the app now (you can already prepare its badge for your Readme, the app will become visible with the next sync around 7 pm UTC, i.e. in less than 5 hours). Nevertheless, answers to each of the bullet-points are much appreciated :wink:

**Comment by zacharee** [comment]
1. Android doesn't have a hard limit on the number of domains an app can support for deep linking, but the framework wasn't designed with apps supporting 1000+ domains in mind, and especially not the 11000+ that Mastodon Redirect has. There are some issues with Mastodon Redirect, for instance, where Chrome will try to query its supported domains and the system server will throw a DeadObjectException because of the size of the list on some devices. Lemmy and PeerTube instance counts are low enough that their Redirect variants don't cause these, but combining them into a single app would mean all of them would have this issue.
2. I can't remember exactly why that's set, but I think it might be so the app can check if passed HTTP-only URLs are media or not through a request.
3. All of the settings/configuration are the same.
4. The screenshots are effectively the same for all the apps. I'll check out making some Fastlane configs.
