### ISSUE TITLE
Play Store listing? 

### ISSUE THREAD

**Issue by tigerhawkvok** [zacharee/MastodonRedirect#10]
With [Advanced Protection](https://support.google.com/accounts/answer/9764949?hl=en#:~:text=When%20you're%20enrolled%20in%20Advanced%20Protection%2C%20harmful%20software%20sources,Google%20Play) on, got to run this with a streamed ADB install which is a PITA

**Comment by zacharee** [comment]
I don't have plans to add it right now. With the number of domains in the manifest, I don't see it getting approved.
