### ISSUE TITLE
"Enable using Shizuku" not working

### ISSUE THREAD

**Issue by njmdietrich** [zacharee/MastodonRedirect#11]
Hi,
pressing on the "Enable using Shizuku" button in LemmyRedirect (v1.3.3) does not appear to do anything. I don't get any UI feedback and the list of supported links remains empty.
I have used Shizuku (v13.5.1) successfully before and the service is running. I also had to manually give LemmyRedirect Shizuku permissions, but it did not change anything.
I am on a Pocophone F1 running Lineage for MicroG 20.

**Comment by zacharee** [comment]
If you uninstall and reinstall the app, does the notice go away? I've noticed Android can have issues where a single domain doesn't get marked as verified, but will suddenly become verified after a clean reinstall.

**Comment by njmdietrich** [comment]
Oh yeah, I just reinstalled it and didn't even have to do anything else for all the supported URLs to show up. Weird, because previously it hadn't shown any (although I think it might have already been working because a feddit.de link opened in infinity without having added any URLs there). Unless you can figure out and fix the exact cause for this, maybe add something in the readme to address the issue?

**Comment by zacharee** [comment]
I added notes to the app and the README. I'm really not sure why it happens. Best guess is Android is freaking out at all the domains.
