### ISSUE TITLE
App crashes my settings app when trying to enable the supported web addresses

### ISSUE THREAD

**Issue by adeptnerd** [zacharee/MastodonRedirect#12]
Hi, so I just discovered this app and was really excited to try this out! But it outright crashes my settings app when I try to enable the URLs for the open supported links setting. 

I have a Samsung M53 5G running One UI 5.1, if that matters.

**Comment by adeptnerd** [comment]
Oh, okay, thanks!! I will check those options out. I just checked, and the Mastodon redirect app doesn't have the Shizuku option. But I will try the link sheet workaround, and hopefully, it works!! 

Also, I didn't see this in a closed issue, so I created a new one! I will close this now; thanks for your quick response!

**Comment by zacharee** [comment]
There should be a card at the top of the app that has a little alert icon and says "Set Up Link Handling". Clicking that will give you the options. Is it not showing up?
