### ISSUE TITLE
Sync not opening mastodon posts correctly

### ISSUE THREAD

**Issue by DavidBurela** [zacharee/MastodonRedirect#13]
Might be a recent change to Sync that prevents it working correctly?

**Summary:** 
When Sync is selected as the Main, it launches sync, but does not open the post. 

**Steps:**
Not working
- Sync selected as the main client in Lemmy Redirect settings
- Open a Lemmy URL with Lemmy redirect
- Sync launches, but does not open the post

Working
- Change main to Liftoff
- Open Lemmy URL
- Liftoff launches, and correctly opens the post

**Comment by zacharee** [comment]
Sync hasn't implemented deep linking yet. The entry point is there, but not the actual processing.
