### ISSUE TITLE
Infinity For Lemmy changed its name.

### ISSUE THREAD

**Issue by Jaoheah** [zacharee/MastodonRedirect#17]
As the title said, It changed its name. Spefically to Eternity. 

As can be seen in its code repo. 

https://codeberg.org/Bazsalanszky/Eternity

And on its latest changelog. 

https://codeberg.org/Bazsalanszky/Eternity/releases/tag/v0.1.0

So this needs to be updated in your app and stuff.

**Comment by zacharee** [comment]
Will be changed in the next release, thanks.
