### ISSUE TITLE
Allow arbitrary PWAs?

### ISSUE THREAD

**Issue by AAGaming00** [zacharee/MastodonRedirect#19]
Would it be possible to allow people to simply redirect to their own instance's URL so it would launch the PWA?

**Comment by zacharee** [comment]
Mastodon and Lemmy don't really have a good way to directly send their default frontends URLs.

Mastodon expects `https://instance/user@domain[/postId]`, which would be possible to construct from a full URL, but only if it's also a Mastodon URL and not Friendica, Pleroma, etc, which use different URL formats.

Lemmy has different post IDs for the same post depending on which instance you're viewing it on. `https://lemmy.world/post/12345` might be `https://lemmy.ml/post/54321` and there's no static way of looking that ID up.

**Comment by AAGaming00** [comment]
Would it be possible to allow some kind of user-specified url template that you replace keywords in

i.e. https://instance.url/objects/%postID or something

**Comment by zacharee** [comment]
That doesn't address the issue of how the app can know what the post ID is from an incoming URL.

**Comment by AAGaming00** [comment]
ah fair
