### ISSUE TITLE
integration in urlcheck

### ISSUE THREAD

**Issue by Martinligabue** [zacharee/MastodonRedirect#2]
Do you think Urlcheck app might be interested in having this list, so that it redirects to the locally installed app?
I'm not sure if in github you can link two apps, but making that file available for them would improve that app too.

https://github.com/TrianguloY/UrlChecker

**Comment by zacharee** [comment]
This is probably something you'd need to bring up with the UrlChecker maintainer. I sourced my list from the https://instances.social API and adapted it for the app manifest.

**Comment by Martinligabue** [comment]
I see, I'll ask them
