### ISSUE TITLE
[Bug] Lemmy Redirect Looping.

### ISSUE THREAD

**Issue by Jaoheah** [zacharee/MastodonRedirect#21]
Description of bug: When I click on the link of certain Lemmy instances it creates some sort of redirect loop, forcing me to close the app to make it stop. 

Video of bug:

https://spectra.video/w/1ixDaQUtxePAHeRkGV7C55

Link to post shown in video: 

https://sh.itjust.works/post/4235860

My Lemmy Instance: https://lemy.lol

Lemmy Client: Eternity v1.1.0

Lemmy Redirect Version: v1.4.3

Link Redirect Method: Shizuku

Shizuku Version: 13.5.1.r1025.ebb2a30

Phone: Samsung Galaxy s23 Ultra (SM-S918U) 

Android Version: 13

One UI Version: 5.1

Android Security Patch: August 1, 2023

**Comment by zacharee** [comment]
If you enable "Open Media in Browser", does it solve the issue?

**Comment by Jaoheah** [comment]
> If you enable "Open Media in Browser", does it solve the issue?

No. That just makes the app crash.

https://spectra.video/w/3YQ3z8sZEk53RH3RML1LTF

**Comment by zacharee** [comment]
Can you enable crash reports or log one manually and send it?

**Comment by Jaoheah** [comment]
> Can you enable crash reports or log one manually and send it?

They're already enabled.

**Comment by zacharee** [comment]
Both issues should be fixed in 1.4.4.
