### ISSUE TITLE
Proper version management in release folder

### ISSUE THREAD

**Issue by Coffee-Viking** [zacharee/MastodonRedirect#24]
Right now, all compiled apk's are named lemmyredirect.apk / mastodonredirect.apk, so on my phone I've got all iterations from lemmyredirect.apk to lemmyredirect(21).apk; which makes it a bit troublesome to refer to the current release - every now and again I download it but forget to install right away, so have to check back (or usually just redownload since it's  easier than manually checking for the version).

Would be neat if the new releases can be named lemmyredirect_1.5.0.apk or something to instantly see the file version.

**Comment by zacharee** [comment]
The next version will have the format `{Variant}Redirect_{Version}-release.apk`.
