### ISSUE TITLE
Support Trunks

### ISSUE THREAD

**Issue by Yahiroz** [zacharee/MastodonRedirect#26]
App: https://play.google.com/store/apps/details?id=com.decad3nce.trunks&hl=en&gl=US

Developer said it supports deep linking, and is willing to provide more information to help: https://mstdn.social/@trunksapp/111362688453115609

**Comment by zacharee** [comment]
I haven't received a reply from the developer about how to send links to Trunks still unfortunately.

**Comment by zacharee** [comment]
The next release of Trunks should hopefully have deep linking support that I can use.

**Comment by zacharee** [comment]
Added in 1.10.0 for Trunks 1.2.13 and later.
