### ISSUE TITLE
Installed Apps are not detected 

### ISSUE THREAD

**Issue by Fauli1221** [zacharee/MastodonRedirect#27]
**Describe the bug**
The app can't detect the installed apps

**To Reproduce**
Open app nothing besides elk can be selected even though I have apps installed

**Expected behavior**
Apps should be detected 

**Device Info:**
 - Device: Fairphone 4 
 - OS: Android 13
 - App Variant: Mastodon Redirect 
 - App Version: 1.9.0
 - Link Method: Shizuku

**Additional context**
![Screenshot_20231128-114551.png](https://github.com/zacharee/MastodonRedirect/assets/43648117/30470613-96fd-464b-8298-309ab9c4bc91)

![Screenshot_20231128-114545.png](https://github.com/zacharee/MastodonRedirect/assets/43648117/67f07983-25d3-4db0-8e4d-313421fe5d1f)

    I already tried restarting my phone

**Comment by zacharee** [comment]
This should be fixed in 1.9.1.

**Comment by Fauli1221** [comment]
Yes 1.9.1 fixed the issue thank you for resolving the issue
