### ISSUE TITLE
Add screenshots to F-Droid

### ISSUE THREAD

**Issue by Korb** [zacharee/MastodonRedirect#28]
https://f-droid.org/packages/dev.zwander.mastodonredirect/

![Screenshot_2023_1206_085608_org fdroid fdroid](https://github.com/zacharee/MastodonRedirect/assets/3509797/9bf4ea12-d8f2-44ae-961f-afb391592e52)

**Comment by RAPXT** [comment]
Screenshots are added. This can be closed.
