### ISSUE TITLE
Please support Phanpy

### ISSUE THREAD

**Issue by onnyyonn** [zacharee/MastodonRedirect#29]
It's a web app with PWA support https://phanpy.social

Would it be possible to open the link in the PWA, if installed, and fallback to open it in the browser otherwise?

**Comment by zacharee** [comment]
Added in 1.11.0.

Phanpy resolves to the host instance, so you need to tap "Take me to my instance" for most links once it's loaded.

**Comment by onnyyonn** [comment]
Thank you so much for such a prompt update.

Would you be open to add support for kbin PWA in Lemmy redirect? If you'd like me to create a separate issue for that, I can do that.

**Comment by zacharee** [comment]
I don't think Kbin supports sending it links. The frontend is also locked to its own instance, unlike Phanpy, so it would be tricky to add.
