### ISSUE TITLE
Support Home Instance Redirects

### ISSUE THREAD

**Issue by fenndev** [zacharee/MastodonRedirect#30]
**Is your feature request related to a problem? Please describe.**
Thunder for Lemmy does not yet support opening links to Lemmy instances that are not your home instance; for example, I'm on `leminal.space` and Thunder for Lemmy cannot open `lemmy.world` links as a result. (Love the app, by the way!)

**Describe the solution you'd like**
I would like an area within Lemmy Redirect to enter your home server address, and have redirected URLs transformed to match the home instance. For example, if I am on `leminal.space` and open https://lemmy.world/c/selfhosted, the URL is transformed to https://leminal.space/c/selfhosted@lemmy.world.

**Describe alternatives you've considered**
The feature could be implemented in Thunder for Lemmy to view communities and magazines that aren't from your home server, but I figured this might be easier to do here and a neat feature.

**Additional context**
![A screenshot of Thunder for Lemmy failing to open the aforementioned link.](https://github.com/zacharee/MastodonRedirect/assets/88926861/d5c46ac4-c35f-4cbd-a4bd-989c1e740361)

**Comment by zacharee** [comment]
Are you on Thunder 0.2.7? I just tested both a post link and a community link on instances other than my own and both opened correctly and let me interact.

**Comment by fenndev** [comment]
Oh, whoops. Didn't realize an update went out. Just tested it myself and it works great. Sorry about that!
