### ISSUE TITLE
Merge Apps?

### ISSUE THREAD

**Issue by dgcampbe** [zacharee/MastodonRedirect#31]
**Is your feature request related to a problem? Please describe.**
I couldn't find an issue already asking or a better place to ask such as a Matrix room,  but is there a reason to have seperate apps for each platform as opposed to just one "Fedi Redirect" app? Sorry for making an issue for a dumb question. :P

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zacharee** [comment]
Check out #8

**Comment by dgcampbe** [comment]
Thanks for the explanation. Sorry for the duplicate issue.
