### ISSUE TITLE
Differentiate both redirect apps better in share menu

### ISSUE THREAD

**Issue by RAPXT** [zacharee/MastodonRedirect#32]
**Is your feature request related to a problem? Please describe.**
As I'm a user of Lemmy and Mastodon, I also use both redirect apps. I've noticed that in the share menu you can't really differentiate which app is for which network. That's confusing and frustrating.

**Describe the solution you'd like**
You should be able to easily differentiate the two apps. Probably the easiest solution would be to add the corresponding network to the apps name in the share menu. Since there are apps that utilize two lines for the app name, maybe you can do it too. My suggestion would be to simply add the networks name under the apps name, e. G. 
first line: Open Link
second line: Mastodon (or Lemmy)

**Describe alternatives you've considered**
Another good way of differentiation would be to allow the user to change the color of the app icon. Although I don't know if this would also change the apps icon color in the share menu or if it would instead use the default color 🤔

Or change the app icons a bit, e. G. add a "Mammoth" for the Mastodon redirect app for easier differentiation.

**Additional context**
Below I've attached a screenshot to demonstrate my problem.
![Screenshot_20240118-015453925](https://github.com/zacharee/MastodonRedirect/assets/53192319/62d12593-3422-4731-abc9-405179ecbfc9)

P.S: Thanks for taking the time to read & developing this nice app 👍

**Comment by zacharee** [comment]
Addressed in 1.12.1 https://github.com/zacharee/MastodonRedirect/releases/tag/1.12.1
