### ISSUE TITLE
Open browser on redirect fail

### ISSUE THREAD

**Issue by FineFindus** [zacharee/MastodonRedirect#5]
If the user clicks on a link but the redirect fails, e.g. if no recognised Mastodon application is installed, nothing happens. This is not a good user experience, I suggest an error message should be displayed and the link should be opened in the browser.

**Comment by zacharee** [comment]
This should be addressed in 1.2.0.

Mastodon Redirect will open a browser if any of these happens:
- The URL passed to it is null, empty, or all whitespace.
- The URL contains "oauth/authorize", indicating it's a login redirect.
- All attempts to launch the selected app fail with an Exception.

I don't think I can reliably detect if the target app starts without throwing an error, but doesn't properly load the given URL.

**Comment by FineFindus** [comment]
Thanks, I think that solves the issue. 

> The URL contains "oauth/authorize", indicating it's a login redirect.

I noticed today that this login does not work when the app is installed. Maybe add an option to disable it? Would also help when navigating the web, e.g. changing settings that are not accessible on the client. Should I create a new issue for this?

**Comment by zacharee** [comment]
I don't think there's a way for me to tell Android which links I *don't* want to handle within a matched domain.

The redirect is to try to maintain original behavior when logging in, where oauth happens through the browser. Which app wasn't working?

**Comment by FineFindus** [comment]
> I don't think there's a way for me to tell Android which links I don't want to handle within a matched domain.

Yes, I fear so. Maybe it is possible to use Shizuku for a workaround?

> Which app wasn't working?

My browser session was corrupted I logged out and was trying to log in, but the app prohibited it, by redirecting me. As a workaround, I removed the app, logged in and installed it again.

**Comment by zacharee** [comment]
I can't reproduce. Logging into androiddev.social doesn't take me to the app.

**Comment by FineFindus** [comment]
My issue wasn't that I was taken to the app, but instead redirected to the same login page. I will keep an eye out for it and create a new issue with more detail if I encounter it again.
