### ISSUE TITLE
[Feature Request] Yuito Support

### ISSUE THREAD

**Issue by moriel5** [zacharee/MastodonRedirect#6]
Since Yuito is a fork of Subway Tooter, I believe that it should not be too hard to add support for Yuito?

**Comment by zacharee** [comment]
Yuito is a fork of Tusky. I can check if the developer has added a share intent.

**Comment by moriel5** [comment]
Thanks, I must have mixed up the source.

That would be awesome.

**Comment by moriel5** [comment]
Hmm... I guess then that I have another issue to open, in that case.

Thanks for looking into this, I'll try to get the dev behind Yuito to look into this.

**Comment by zacharee** [comment]
Closing as a duplicate of #23 for better tracking.
