### ISSUE TITLE
[Feature Request] add support for the official mastodon app

### ISSUE THREAD

**Issue by Cris-Edmundson** [zacharee/MastodonRedirect#9]
I'd love it if the official mastodon app could be supported, assuming its possible from a technical standpoint 

Official app https://www.f-droid.org/packages/org.joinmastodon.android/

**Comment by zacharee** [comment]
The last time I checked, they didn't have way to open links externally

**Comment by zacharee** [comment]
Checking again and it looks like they do have support now, so this will be in the next release.

**Comment by zacharee** [comment]
https://github.com/zacharee/MastodonRedirect/releases/tag/1.3.3
